### ISSUE TITLE
RIP my Samsung Notes just Hangs and Crashes

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [kellwinr/galaxybook_mask#1]
After installing this, it crashes my Samsung Notes LOL

**Comment by kellwinr** [comment]
The script is working fine on my side, try updating the application via the Microsoft Store if there's any updates. If not, you may try to reinstall the application back using winget alone.

**Comment by ENTPRESTIGIOUS** [comment]
> The script is working fine on my side, try updating the application via the Microsoft Store if there's any updates. If not, you may try to reinstall the application back using winget alone.

Yeah I might to reinstall.
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/14d20e24-bc2e-4a27-b04b-776e8fb49d33)

**Comment by kellwinr** [comment]
> > The script is working fine on my side, try updating the application via the Microsoft Store if there's any updates. If not, you may try to reinstall the application back using winget alone.
> 
> Yeah I might to reinstall because it just hangs.

Let me know the result after you've done reinstalling yah.

**Comment by kellwinr** [comment]
I am going to close this issue in a few hours if there is no follow-up

**Comment by ENTPRESTIGIOUS** [comment]
Microsoft store said it just updated and now I'm back to having the dialogue saying that it works for galaxy books. Tried to run the script again, didn't work. I don't know why asks me on how to open the .vbs file. Isn't it a Microsoft default for Visual Basic?

**Comment by ENTPRESTIGIOUS** [comment]
Also, the changes were successfully made in the Registry Editor yesterday which was crashing.

**Comment by kellwinr** [comment]
the script is just a normal batch file. Just run it with terminal or cmd. If the application kept crashing, you should try to reinstall the application again. And your registry was crashing?

**Comment by ENTPRESTIGIOUS** [comment]
> the script is just a normal batch file. Just run it with terminal or cmd. If the application kept crashing, you should try to reinstall the application again. And your registry was crashing?

No the registry wasn't crashing, Samsung Notes was crashing. Yeah I double clicked it and command prompt opened up but then shortly after it asks on how to open a .vbs file.

**Comment by kellwinr** [comment]
Regarding the .vbs thing, if you check the script, it has nothing to do with it. After running the script, the cmd should closed itself automatically, and that's all.
Anyways, it all worked out in the end?

**Comment by ENTPRESTIGIOUS** [comment]
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/399d31b2-d69c-4939-bdba-754b388daa38)

**Comment by ENTPRESTIGIOUS** [comment]
i used Microsoft Windows Based Script Host and now it's hanging again
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/66eb71c9-b38a-45b3-9d84-834d83f1c151)

**Comment by ENTPRESTIGIOUS** [comment]
If I don't choose anything, nothing happens. It keeps saying that it's for Galaxy Books.

**Comment by kellwinr** [comment]
Then I think the vbs popup is the be the UAC ShellExecute, used to gain admin permission when running the batch. However, your situation is rather strange, you can try removing the top section, leaving "`reg add ....`"  and "`exit`". But this UACShellExecute VBS is important if you use the batch with startup. If this is the case, you should use the one with no startup, run the batch file once every time your pc boots up.

**Comment by ENTPRESTIGIOUS** [comment]
> Then I think the vbs popup is the be the UAC ShellExecute, used to gain admin permission when running the batch. However, your situation is rather strange, you can try removing the top section, leaving "`reg add ....`" and "`exit`". But this UACShellExecute VBS is important if you use the batch with startup. If this is the case, you should use the one with no startup, run the batch file yourself as administrator once every time your pc boots up.

Oh shoot sry I forgot to mention that i was using the no startup version. Just ran the batch file using Admin perms and it didn't ask for vbs. Tried opening it just now but hangs :(

**Comment by kellwinr** [comment]
Samsung Note hangs?

**Comment by ENTPRESTIGIOUS** [comment]
Yeah proceeding to reinstall

**Comment by ENTPRESTIGIOUS** [comment]
Great I can't even install it now...this is so painful.
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/2c6b9b34-2e74-4ea4-beef-a37dc6a2218b)

**Comment by kellwinr** [comment]
> Great I can't even install it now...this is so painful. ![image](https://user-images.githubusercontent.com/45579671/265583277-2c6b9b34-2e74-4ea4-beef-a37dc6a2218b.png)

use winget

**Comment by ENTPRESTIGIOUS** [comment]
> > Great I can't even install it now...this is so painful. ![image](https://user-images.githubusercontent.com/45579671/265583277-2c6b9b34-2e74-4ea4-beef-a37dc6a2218b.png)
> 
> use winget

yep, using that right now

**Comment by ENTPRESTIGIOUS** [comment]
It's funny that the install button used to show up after "winget"ting the first time.

**Comment by ENTPRESTIGIOUS** [comment]
LOL there's no dialogue for galaxy books now but it tells me to install Samsung Account LOOL
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/45d952e4-6850-4918-a7fd-e3c49c2ec902)

**Comment by ENTPRESTIGIOUS** [comment]
Ok i'm in now.
![image](https://github.com/kellwinr/galaxybook_mask/assets/45579671/b2145ef5-2b6f-4e29-9dd1-01ba75dac475)
