### ISSUE TITLE
Direct launch script doesn't work consistently

### ISSUE THREAD

**Issue by justin13888** [kellwinr/galaxybook_mask#10]
**Context:** I've been trying to run Samsung Notes (on a non Samsung PC of course) using the [direct launch script](https://github.com/kellwinr/galaxybook_mask/blob/main/samsungnotes-directlaunch.bat)

**Problem:** It's great that it works most of the time! But it doesn't occasionally which I believe is because the timeout is set too low. I changed the timeout from 2s to 5s which made it consistently work now.

![image](https://github.com/kellwinr/galaxybook_mask/assets/20733699/9e8b276a-0562-4737-a90d-3f3d0780d4c2)

**Solution:** Update the 2s timeout to 5s in the script

**Comment by kellwinr** [comment]
@ahmadalli your change is set from 2s to 10s, isn't that too long, or it somehow performed better than 5s?

**Comment by justin13888** [comment]
I found 5s works consistently. The only difference in practice is that the shell running the script stays open longer which might be annoying.

**Comment by ahmadalli** [comment]
> isn't that too long

I haven't tested it with 5s, but my thinking is that the app might take longer to do the initial check and the extra wait wouldn't hurt much
