### ISSUE TITLE
How to uninstall the startup version?

### ISSUE THREAD

**Issue by AnopheliaMiratio** [kellwinr/galaxybook_mask#19]
Hi there! This has been a revelation, because just as I got to start using Samsung Notes to access my notes on my computer, Samsung updated it to block out non-galaxybook devices.

My problem is that I am really annoyed by the permissions asked at startup every time and I was wondering how I can remove it. I'm thinking of using the direct-launch version instead.

**Comment by kellwinr** [comment]
### To undo the changes (startup bat), locate & delete, then restart pc, the registry values will revert back to factory values

`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\GalaxyBookMask.bat`
