### ISSUE TITLE
Samsung Device Care not fully working

### ISSUE THREAD

**Issue by raddekk** [kellwinr/galaxybook_mask#30]
The Samsung Device Care app boots up, but the whole app is broken, it doesn't detect any photos, videos, etc. and it can't make a backup.
![image](https://github.com/kellwinr/galaxybook_mask/assets/167124012/8db7122a-bf66-4644-a89c-967d71f92455)

**Comment by kellwinr** [comment]
Hi, this requires more modification to the system and only specific hardwares (particularly wireless drivers) to work, you may have a look at this [Forum](https://xdaforums.com/t/how-to-samsung-multi-control-with-non-samsung-windows-pc.4640205/). This repo focuses more on Samsung Notes, it might unlock some other Samsung apps but it will not work perfectly.

**Comment by kellwinr** [comment]
closing since this is not an issue, kindly refer to the provided Forum link
