### ISSUE TITLE
How to delete this script?

### ISSUE THREAD

**Issue by 0Les-lie0** [kellwinr/galaxybook_mask#31]
I can't delete this script. I have tried to delete the file that I downloaded, it seems that I make it. But every time I open my computer, it will ask me whether I want to start this script like before, it's bothering. If anyone can help me, I'd be very grateful.

**Comment by avimakkar** [comment]
Delete the batch file here
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\GalaxyBookMask.bat

**Comment by 0Les-lie0** [comment]
> Delete the batch file here C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\GalaxyBookMask.bat

Thank you for your comments.
