### ISSUE TITLE
Antivirus False Positive

### ISSUE THREAD

**Issue by Aldebrand13** [kellwinr/galaxybook_mask#35]
I ran this file first before I got Bitdefender, now that I have it it's being flagged as a false positive for Malware/Malicious Software. I did send the file (and the link to this page, so that they can view all the other files) so hopefully, at least with Bitdefender, it no longer gets flagged. 

I had AVG Premium before this, and it was not flagged. I do not have any other antivirus to test it with, but it's a heads up that perhaps the files should be given to other antivirus companies, so that this problem doesn't continue to happen for other users. Though seeing as how this is the first time the issue has been reported, I can't imagine it's that widespread. 
![image](https://github.com/kellwinr/galaxybook_mask/assets/37649031/9273ee81-aa9c-473c-aede-d35d89cc3385)

**Comment by Liam2349** [comment]
The best solution is to get rid of the third-party antivirus software and just run Defender. Almost everything else is completely unnecessary and is very often detrimental.
