### ISSUE TITLE
More apps

### ISSUE THREAD

**Issue by easynote** [kellwinr/galaxybook_mask#37]
Its possible to make this compatible with all samsung apps for windows like samsung pass?

Thanks

**Comment by kellwinr** [comment]
It is possible only when your hardware (specifically wireless drivers) supports it. You may refer to this https://xdaforums.com/t/how-to-samsung-multi-control-with-non-samsung-windows-pc.4640205/

**Comment by kellwinr** [comment]
Closing since it is not an issue, please refer to the link provided regarding your enquiry. Thank you.
