### ISSUE TITLE
How to Uninstall The Script?

### ISSUE THREAD

**Issue by Edaryion** [kellwinr/galaxybook_mask#41]
Hi. I no longer use Samsung Notes. Alas, this script asks for my permission to run every time I turn on the computer. How do I remove it?

**Comment by kellwinr** [comment]
### To undo the changes (startup bat), locate & delete, then restart pc, the registry values will revert back to factory values

just delete the one .bat file
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\GalaxyBookMask.bat`

**Comment by Edaryion** [comment]
Thank you for the solution.
