### ISSUE TITLE
please add support for Samsung Pass

### ISSUE THREAD

**Issue by lazymonkey2** [kellwinr/galaxybook_mask#9]
I installed Samsung Pass from here:
https://apps.microsoft.com/detail/samsung-pass/9MVWDZ5KX9LH?hl=en-us
but even with your script it doesn't work: it says that the computer doesn't support Samsung Pass.

**Comment by kellwinr** [comment]
The script only works for Samsung Notes & Acconts

**Comment by mooock** [comment]
just to confirm that samsung pass does only work with samsung products, its showed like it now was open for any computer with a new windows 11 and TPM 2.0 but from this link it states clear that it only supports Galaxy Book 3 and above

https://www.samsung.com/levant/support/apps-services/how-to-use-samsung-pass-on-galaxy-book/

for this the spoof does not work. as i spoke with samsung support, they intent to only provide support for their own products
